### ISSUE TITLE
Centralised Exchange Trading

### ISSUE THREAD

**Issue by ThaneCoin** [stellar-expert/stellar-expert-explorer#480]
Is there a way for stellar expert explorer to connect to centralised exchanges and update trading volumes on explorer.

**Comment by orbitlens** [comment]
The explorer shows only on-chain data. Pulling trading volumes from external sources is out of scope, and won't be implemented in the foreseeable future.

**Comment by ThaneCoin** [comment]
Thank you orbitlens for the reply.
