### ISSUE TITLE
e.toFQAN is not a function error displayed

### ISSUE THREAD

**Issue by katherinaGo** [stellar-expert/stellar-expert-explorer#538]
![image](https://user-images.githubusercontent.com/53235867/134889009-0c29d4ba-f733-43ed-8af5-2174f3495e21.png)
When check my public GAGANT47Q3U34D4M7W5R5RFZWDKDLOFKKSFMWZ4J6PHF3TQSJY2FL5IF, get the error message below.

**Comment by orbitlens** [comment]
Fixed. Thanks for letting us know.
