### ISSUE TITLE
explorer no longer updating operations/transactions on account or asset view.

### ISSUE THREAD

**Issue by hackbyte** [stellar-expert/stellar-expert-explorer#567]
When looking into my account using stellar.expert, the last shown transaction seems to be from 2021-11-23 09:12:34 UTC and it looks like there was nothing more happening since then.

The same is true if i look into an asset, like XLM for example. There to, the last shown transaction claims to be from 2021-11-23 09:13:51 UTC..

Anything up on your database maybe? Live transaction log is still updating .. but not reflecting in the detail pages..

**Comment by Jonas-SRB** [comment]
same on my end, can't retrieve live info

**Comment by remarkablemayonaise** [comment]
Made the same comment. Annoying when doing complicated stuff with labs.

**Comment by orbitlens** [comment]
Hello,

One of our Stellar Core nodes fell out of consensus, which led to the disruption of our historical data ingestion process. We addressed the root problem, and the service has been restored today around 2AM UTC.

Sorry for the inconvenience.
