### ISSUE TITLE
Missing Assets and Transactions

### ISSUE THREAD

**Issue by remarkablemayonaise** [stellar-expert/stellar-expert-explorer#568]
Stellar Expert is missing assets and transactions:

https://stellar.expert/explorer/public/tx/d60714281e7575dd35dd3c2fb1e25f5ea51982ffc1804b93f235a7471bc7c715

I issued an asset which seemed successful. The asset is on Stellar Laboratories (Horizon) https://horizon.stellar.org/assets?asset_code=MayoCoin&asset_issuer=GC5TLOYRAEXMHSJ5H3CZYZVT22IZSDANO2COJLSCSVMZZRS7QUPXM6QT

but not on Stellar laboratory https://stellar.expert/explorer/public/asset/MayoCoin-GC5TLOYRAEXMHSJ5H3CZYZVT22IZSDANO2COJLSCSVMZZRS7QUPXM6QT

My account seems to have frozen too https://stellar.expert/explorer/public/account/GAUCEMTLRZ6G3YJWUMRNFCWJEFXVPDIYQG6S3R6VCLSRBIIQBVLPZ53D

These transactions are on Albedo

 Transaction 247cb239…ff3cc8a7
12m ago
Pay 0.5000000 XLM to GC5T…M6QT
 Transaction d6071428…1bc7c715
26m ago
Pay 18,778,580,398.0000000 MayoCoinGC5T…M6QT to GAUC…Z53D
 Transaction aedab41e…e11bee64
28m ago
Create trustline for MayoCoinGC5T…M6QT with limit 18,778,580,398.0000000 MayoCoinGC5T…M6QT
 Transaction a6e3473f…9292a3b0
33m ago
Merge account GA2W…LDMS into account GAUC…Z53D
 Transaction 52d6d25c…776a80de
38m ago
Pay 3.0000000 XLM to GC5T…M6QT
 Transaction 506486f6…a20ce059
40m ago
Merge account GAIX…GLWR into account GAUC…Z53D
 Transaction d2dba4e4…838c6fce
47m ago
Create account GAIX…GLWR with starting balance 3.0000000 XLM

**Comment by orbitlens** [comment]
Hello,

One of our Stellar Core nodes fell out of consensus, which led to the disruption of our historical data ingestion process. We addressed the root problem, and the service has been restored today around 2AM UTC.

Sorry for the inconvenience.

ref #567
