### ISSUE TITLE
Hard to understand individual trades in path payment

### ISSUE THREAD

**Issue by s-a-y** [stellar-expert/stellar-expert-explorer#636]
It looks like all trade effects are shown for path payments, not filtered by the account, so a user sees both sides of the trade, which makes it hard to understand what really happened
<img width="1334" alt="Screen Shot 2022-04-18 at 8 36 35 am" src="https://user-images.githubusercontent.com/1667781/163734861-7c003aea-8cf7-4c8f-8b84-7a98f2a95539.png">

Proposed solution: filter trade effects by `account`.
Only effects 1. 2. 4. 6. 8. should stay after that

**Comment by orbitlens** [comment]
We really need to display both sides of trades here for the sake of clarity (in a wallet interface the suggestion to hide the counterparty of the trade would truly make much more sense), but I definitely agree with you that the interface is misleading here. I added an account address to each of the trade effects to show trade parties unambiguously.

**Comment by s-a-y** [comment]
Well, I still believe that when I'm looking at the account I want to only see effects associated with that specific account. It's not a payment that has 2 sides: from and to. It's an effect of transaction on a specific account.

**Comment by s-a-y** [comment]
Also this (for swap in liquidity pool):
<img width="1327" alt="Screen Shot 2022-05-16 at 11 45 58 pm" src="https://user-images.githubusercontent.com/1667781/168607028-afaec71b-b79e-4798-80f5-433d94063c08.png">

Not sure, maybe supposed to be a separate issue, but the end result is the same, hard to understand what's going on:
First it says BTC converted to USDT, then it says USDT converted to BTC

**Comment by orbitlens** [comment]
Done. Updated description for `trade` and `liquidity_pool_trade` effects as proposed.
Thanks  :+1:
