### ISSUE TITLE
Error when loading claim claimable balance op

### ISSUE THREAD

**Issue by tomerweller** [stellar-expert/stellar-expert-explorer#644]
To recreate: go to [this transaction](https://stellar.expert/explorer/public/tx/7cefdf742979e50626fad0b073e11791bf01211c8db0da0fe284db72116b405c) and try to expand the `ClaimClaimableBalance` infromation

![image](https://user-images.githubusercontent.com/815704/168451729-8f7e8916-2bde-4d1e-9c77-ddc3ea05ecd4.png)

**Comment by orbitlens** [comment]
Fixed
