### ISSUE TITLE
Asset logos not displaying on Stellar Expert

### ISSUE THREAD

**Issue by Afreum** [stellar-expert/stellar-expert-explorer#646]
Logos for assets are not displayed on Stellar Expert  if the logos were not found (e.g. 403 error) the first time Stellar Expert parsed the stellar.toml file. Even after the not found errors are fixed, no asset logos are not displayed but the currency info includes the link to the correct logo file. This can be easily fixed by parsing the stellar.toml at set intervals and updating your database  if any changes or using the actual logo as provided in the stellar.toml at runtime.

**Comment by orbitlens** [comment]
We don't cache asset logo images (yet), so the problem is caused by your browser which cached the 403 response. I can see a logo of your asset on my machine. You can view the asset page in incognito mode to make sure everything works as expected.

**Comment by Afreum** [comment]
Noted. Will check. Thanks.

**Comment by Afreum** [comment]
Checked in incognito and the logos are still not showing. Here is an example of only 2 logos showing: https://stellar.expert/explorer/public/account/GCJFH6HI5UPQVTUUOAS7JPOEPCQZCNGM63GWMBL6ULGUL4XUXRIXXIEQ
