### ISSUE TITLE
Open API Docs link in footer leads to 404 page

### ISSUE THREAD

**Issue by grempe** [stellar-expert/stellar-expert-explorer#673]
At the bottom of pages, in the footer, is a link to "Open API docs":

https://stellar.expert/explorer/testnet/tx/2f6da192e5e3b0741695a588dbe4f41a46a5ec93ec2fb1d5aec6a86024553fc7

It links to this page, which returns a 404

https://stellar.expert/openapi.html

**Comment by orbitlens** [comment]
Couldn't reproduce. Possibly a temporary deploy script issue.
