### ISSUE TITLE
Calculation error in Liquidity pools in Total value locked

### ISSUE THREAD

**Issue by jorgekatrich** [stellar-expert/stellar-expert-explorer#679]
![Err Pool](https://user-images.githubusercontent.com/17133044/188074182-63962b72-30d9-402e-8d7b-c0652438fcfd.png)
![Err Pool2](https://user-images.githubusercontent.com/17133044/188074647-cc8808fd-24ca-495b-a590-8f953a094820.png)
![Err Pool3](https://user-images.githubusercontent.com/17133044/188076112-568c5599-7f63-4022-8a49-5d709a73da33.png)

**Comment by orbitlens** [comment]
Fixed. Thanks for the report!
