### ISSUE TITLE
Invalid asset name: undefined

### ISSUE THREAD

**Issue by lawlietseth** [stellar-expert/stellar-expert-explorer#681]
Hi, I would like to inquire about this issue wherein we encountered an Invalid asset name: undefined on our stellar address GBIJTZVWS6GSTEDGF4V6TKVZ6N7SJXWTWCLGFH66RN5A6RW7OVCLSGFF

**Comment by fastepic** [comment]
I have the same error for EPIC ( fastepic.eu )
"Invalid asset name: undefined." at https://stellar.expert/explorer/public/asset/EPIC-GD4YEDHMQK2HD7DMKAG554JK4TVOTQNPWTKR2KHL5UCSJ6ART2UA2E32-1

c@https://stellar.expert/212.18acec95c0d7039b280c2c54176aad42.js:2:7620
parse@https://stellar.expert/212.18acec95c0d7039b280c2c54176aad42.js:2:8804
@https://stellar.expert/212.18acec95c0d7039b280c2c54176aad42.js:2:20975
b@https://stellar.expert/212.18acec95c0d7039b280c2c54176aad42.js:2:20962
sa@https://stellar.expert/app.7f31f1f39850c68c2484.js:2:124010
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0

**Comment by lawlietseth** [comment]
@fastepic yours is ok now, i checked it. how did you do it?

**Comment by culturebets** [comment]
Good day,

I have an issue as well. I received the same

Here is from my **tpgtoken.io Distribution Account**:
GBIJTZVWS6GSTEDGF4V6TKVZ6N7SJXWTWCLGFH66RN5A6RW7OVCLSGFF


"Invalid asset name: undefined." at https://stellar.expert/explorer/public/account/GBIJTZVWS6GSTEDGF4V6TKVZ6N7SJXWTWCLGFH66RN5A6RW7OVCLSGFF?filter=all
TypeError: Invalid asset name: undefined.
    at new c (https://stellar.expert/212.18acec95c0d7039b280c2c54176aad42.js:2:7620)
    at c.parse (https://stellar.expert/212.18acec95c0d7039b280c2c54176aad42.js:2:8804)
    at https://stellar.expert/212.18acec95c0d7039b280c2c54176aad42.js:2:20975
    at Array.map (<anonymous>)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33


======================

and here is from my **tpgtoken.io Issuer Account**:

GANJHXWRSHC6AQDG3S4LW3VIM5HOKOSOGWJJPUXE7RJLEZNGMJ33ELS6

"Invalid asset name: undefined." at https://stellar.expert/explorer/public/asset/TPG-GANJHXWRSHC6AQDG3S4LW3VIM5HOKOSOGWJJPUXE7RJLEZNGMJ33ELS6?filter=all
TypeError: Invalid asset name: undefined.
    at new c (https://stellar.expert/212.18acec95c0d7039b280c2c54176aad42.js:2:7620)
    at c.parse (https://stellar.expert/212.18acec95c0d7039b280c2c54176aad42.js:2:8804)
    at https://stellar.expert/212.18acec95c0d7039b280c2c54176aad42.js:2:20975
    at Array.map (<anonymous>)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33


Please let me know what caused this error and how it can be fixed? Any updates would be helpful.

our email is admin@tpgtoken.io

Thank you so much!

**Comment by orbitlens** [comment]
The problem was caused by a metadata-related update we rolled out recently.
Everything has been fixed, asset and liquidity pools metadata remain backwards-compatible.

Sorry for the inconvenience.

**Comment by BrendanEyles** [comment]
"Cannot read properties of undefined (reading 'find')" at https://stellar.expert/explorer/public/account/GDBXCWE52NKAPPCP6LYNFLADNDGH6Q6FPGRS42MN4YNIDGSQGL46K5G6
TypeError: Cannot read properties of undefined (reading 'find')
    at https://stellar.expert/explorer.a4ec1dcb347e6cd992c09396f59db808.js:1:23810
    at aa (https://stellar.expert/app.e67c0ab26dca498f8264.js:2:432718)
    at Ka (https://stellar.expert/app.e67c0ab26dca498f8264.js:2:442236)
    at Ws (https://stellar.expert/app.e67c0ab26dca498f8264.js:2:485817)
    at Cu (https://stellar.expert/app.e67c0ab26dca498f8264.js:2:472121)
    at Ou (https://stellar.expert/app.e67c0ab26dca498f8264.js:2:472049)
    at Au (https://stellar.expert/app.e67c0ab26dca498f8264.js:2:471912)
    at bu (https://stellar.expert/app.e67c0ab26dca498f8264.js:2:468899)
    at https://stellar.expert/app.e67c0ab26dca498f8264.js:2:418637
    at t.unstable_runWithPriority (https://stellar.expert/app.e67c0ab26dca498f8264.js:2:513298)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

Get this unhandled error on my account balance
