### ISSUE TITLE
Unhandled error occurred

### ISSUE THREAD

**Issue by remarkablemayonaise** [stellar-expert/stellar-expert-explorer#682]
My lovely liquidity pool is inaccessible!

https://stellar.expert/explorer/public/liquidity-pool/db0d8178b18956afcda07394288d216eff73fa9f3db1dd19f73c9b3ae6e4f5fb?filter=asset-holders

"Invalid asset name: undefined." at https://stellar.expert/explorer/public/liquidity-pool/db0d8178b18956afcda07394288d216eff73fa9f3db1dd19f73c9b3ae6e4f5fb?filter=asset-holders
TypeError: Invalid asset name: undefined.
    at new c (https://stellar.expert/212.18acec95c0d7039b280c2c54176aad42.js:2:7620)
    at c.parse (https://stellar.expert/212.18acec95c0d7039b280c2c54176aad42.js:2:8804)
    at https://stellar.expert/212.18acec95c0d7039b280c2c54176aad42.js:2:20975
    at Array.map (<anonymous>)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

Please send help!

**Comment by orbitlens** [comment]
The problem was caused by a metadata-related update we rolled out recently.
Everything has been fixed, asset and liquidity pools metadata remain backwards-compatible.

Sorry for the inconvenience.

**Comment by orbitlens** [comment]
ref #681
