### ISSUE TITLE
"Invalid asset name: undefined."at --- ERROR

### ISSUE THREAD

**Issue by culturebets** [stellar-expert/stellar-expert-explorer#683]
Good day,

I have an issue as well. I received the same

Here is from my tpgtoken.io Distribution Account:
GBIJTZVWS6GSTEDGF4V6TKVZ6N7SJXWTWCLGFH66RN5A6RW7OVCLSGFF

"Invalid asset name: undefined." at https://stellar.expert/explorer/public/account/GBIJTZVWS6GSTEDGF4V6TKVZ6N7SJXWTWCLGFH66RN5A6RW7OVCLSGFF?filter=all
TypeError: Invalid asset name: undefined.
at new c (https://stellar.expert/212.18acec95c0d7039b280c2c54176aad42.js:2:7620)
at c.parse (https://stellar.expert/212.18acec95c0d7039b280c2c54176aad42.js:2:8804)
at https://stellar.expert/212.18acec95c0d7039b280c2c54176aad42.js:2:20975
at Array.map ()
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33

======================

and here is from my tpgtoken.io Issuer Account:

GANJHXWRSHC6AQDG3S4LW3VIM5HOKOSOGWJJPUXE7RJLEZNGMJ33ELS6

"Invalid asset name: undefined." at https://stellar.expert/explorer/public/asset/TPG-GANJHXWRSHC6AQDG3S4LW3VIM5HOKOSOGWJJPUXE7RJLEZNGMJ33ELS6?filter=all
TypeError: Invalid asset name: undefined.
at new c (https://stellar.expert/212.18acec95c0d7039b280c2c54176aad42.js:2:7620)
at c.parse (https://stellar.expert/212.18acec95c0d7039b280c2c54176aad42.js:2:8804)
at https://stellar.expert/212.18acec95c0d7039b280c2c54176aad42.js:2:20975
at Array.map ()
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33

Please let me know what caused this error and how it can be fixed? Any updates would be helpful.

our email is [admin@tpgtoken.io](mailto:admin@tpgtoken.io)

Thank you so much!

**Comment by orbitlens** [comment]
The problem was caused by a metadata-related update we rolled out recently.
Everything has been fixed, asset and liquidity pools metadata remain backwards-compatible.

Sorry for the inconvenience.

**Comment by orbitlens** [comment]
ref #681

**Comment by culturebets** [comment]
> 
Thank you so much for your immediate response. I'm so glad everything is fixed. Thank you @orbitlens

**Comment by culturebets** [comment]
Thank you so much for your immediate response. I'm so glad everything is
fixed. Thank you @orbitlens

Sincerely,
Mike Sta.Ana
CEO TPG

**Comment by JFWooten4** [comment]
This also seems to break viewing accounts with certain multi-sig setups:
https://stellar.expert/explorer/public/account/GD2OUJ4QKAPESM2NVGREBZTLFJYMLPCGSUHZVRMTQMF5T34UODVHPRCY

**Comment by orbitlens** [comment]
> This also seems to break viewing accounts with certain multi-sig setups: https://stellar.expert/explorer/public/account/GD2OUJ4QKAPESM2NVGREBZTLFJYMLPCGSUHZVRMTQMF5T34UODVHPRCY

Fixed. Thanks for letting us know @JFWooten4
