### ISSUE TITLE
Paging tokens on API are causing errors

### ISSUE THREAD

**Issue by hypersoniq** [stellar-expert/stellar-expert-explorer#697]
When pulling a list of asset holders, API calls using paging tokens are failing if the paging token contains a '+', for example AAAAAATfr9wAjA+8
Same problem with the horizon API as well. Any ideas?
you can see the error result with this url...
[https://api.stellar.expert/explorer/public/asset/XLPG-GDDRETFPCQIDWH3LNMIONXSSBWYLXZFSF3WY6UCCIF6NMTW2UKA3R4NX/holders?order=desc&limit=200&cursor=AAAAAc+sAfgAje24](https://api.stellar.expert/explorer/public/asset/XLPG-GDDRETFPCQIDWH3LNMIONXSSBWYLXZFSF3WY6UCCIF6NMTW2UKA3R4NX/holders?order=desc&limit=200&cursor=AAAAAc+sAfgAje24)

**Comment by greg9762** [comment]
Same here

**Comment by orbitlens** [comment]
When you provide `cursor` parameter (or any other URL parameter for what it's worth), the value always should be URL-encoded. In the browser environment, it should look like `encodeURIComponent(paging_token)`. So the URL will look like this:

https://api.stellar.expert/explorer/public/asset/XLPG-GDDRETFPCQIDWH3LNMIONXSSBWYLXZFSF3WY6UCCIF6NMTW2UKA3R4NX/holders?order=desc&limit=200&cursor=AAAAAc%2BsAfgAje24
