### ISSUE TITLE
[Testnet] The asset does not exist on the ledger

### ISSUE THREAD

**Issue by csokun** [stellar-expert/stellar-expert-explorer#700]
Hi,

I'm issued a new asset on Testnet. I can see the asset under my issuer account https://stellar.expert/explorer/testnet/account/GAQW4HBQ2BAGKUA3VHGDXFIB5TTFH6DTITJIQMGPGO4NZQMOO5DBXKVT 
![image](https://user-images.githubusercontent.com/29750/197902999-eea8180e-e389-45b4-96e5-dc40be926a83.png)

However, when I clicked on the asset https://stellar.expert/explorer/testnet/asset/KVT-GAQW4HBQ2BAGKUA3VHGDXFIB5TTFH6DTITJIQMGPGO4NZQMOO5DBXKVT 
![image](https://user-images.githubusercontent.com/29750/197902932-a157bba2-ff31-422d-83ed-fc8963c1a032.png)

**Comment by hbirkdale** [comment]
@csokun What happened with this issue?
