### ISSUE TITLE
Refractor down?

### ISSUE THREAD

**Issue by remarkablemayonaise** [stellar-expert/stellar-expert-explorer#705]
Am trying to sort out a refractor multi sig transaction using https://refractor.stellar.expert/tx/add Any ideas what's wrong?

**Comment by orbitlens** [comment]
Sorry for the temporary outage. It's a DNS issue.
We moved Refractor to the new dedicated server and updated DNS records accordingly, but there are some technical problems on the side of our service provider. Still working on this.

**Comment by orbitlens** [comment]
We finally sorted out DNS issues. Refractor is back online.
My apologies for the prolonged service disruption. We always try to fix such critical problems asap, but this time we had problems with third-party services.
