### ISSUE TITLE
Newly Minted Token Receives this = Warning: reported for illicit or fraudulent activity

### ISSUE THREAD

**Issue by Codenatics-SA** [stellar-expert/stellar-expert-explorer#724]
I have minted a token called "DJCK" https://stellar.expert/explorer/public/asset/DJCK-GAZ7O7CUOUGXJYBPNYTB6NCPMX5DQLJW3UFE5XYKRSUI2NFJNDQ7T6FI-1

A few minutes later the token was marked as fraudulent. There is no response from stellar.expert, how can we rectify this as our asset is not fraudulant or Scam.

**Comment by CryptoHobbyist** [comment]
Hello @Codenatics-SA 
This should be rectified after review. The initial issue was that at the time of minting this token was using the logo for doublejack, but the doublejack.world site was only one page without information, and was asking for email and phone numbers (signs of phishing). At the time there was no connections/links from doublejack.online or doublejack.club.

It has now been verified that the doublejack.world tokens are connected to the doublejack.online and doublejack.club sites. Whether these sites are legal in different countries factual are not being looked into. I am still having trouble getting any replies from any of the organizations to verify your donations to their charities and I could not find the audit information. It should be registered with the government of Curacao. Do you have any links to their government registries and audit of gaming?

looking Towards The Future With You,
Rob TheCryptoHobbyist

**Comment by CryptoHobbyist** [comment]
I have also tried to make contact with all the claimed charities that are claimed by doublejack.online and doublejack.club and 2 are unreachable (dead) and only one responded to report that they have not received any revenue from them as of yet.

**Comment by Codenatics-SA** [comment]
Hi CryptoHobbyist,

doublejack a platform that supports charities, sports teams and Individuals to earn money and support themselves. 

At the end of the day it does come down to working with us and engaging with there followers to grow their communities. This allows the organisations to automate and elevate there fundraising with us.
We do not discuss our clients nor the Funding amount of those clients, nor do our clients wish us to reveal / leak the funding amounts. This is upon their very own discretion, for obvious reasons.

To get into more detail please watch this video: https://youtu.be/PHryQkaGYMI

You too can support a charity of choice or create your own charity with us. So that you can engage with your community to grow and help those around you.

If you would like you are more than welcome to join us in a training course to get started.


Best regards,

**Comment by CryptoHobbyist** [comment]
@Codenatics-SA 
Do you have any kind of audit report posted? What is the purpose in your current platforms of DoubleJack gambling offerings for this token? Was there a specific reason to add a third domain to this system?
Rob
