### ISSUE TITLE
XLM supply error?

### ISSUE THREAD

**Issue by GitBatRat** [stellar-expert/stellar-expert-explorer#766]
https://stellar.expert/explorer/public/network-activity

Why did the XLM supply number shoot up to > 100B circa June 19?  Looks like an error (I hope) since supply cap is 50B.

Thanks for all you do on this site.  It is a great tool.

**Comment by GitBatRat** [comment]
The XLM supply is still listed at 105 billion

 https://stellar.expert/explorer/public/network-activity

<iframe onLoad="var c=this;window.addEventListener('message',function({data,source}){if(c&&source===c.contentWindow&&data.widget===c.src)c.style.height=data.height+'px'},false);" src="https://stellar.expert/widget/public/network-activity/supply-fee" style="border:none;overflow:hidden;max-width:100%; min-width:300px;max-height:100%;min-height:200px;width:100%"></iframe>

**Comment by GitBatRat** [comment]
Circulating XLM Supply still listed at 105 billion

**Comment by orbitlens** [comment]
Fixed. Thanks for the heads up! And sorry for the delay.

**Comment by GitBatRat** [comment]
Thanks for the amazing work!  Stellar is an amazing project, and your site is incredibly helpful.
