### ISSUE TITLE
Overall traded volume is 0 USD on stellar.expert

### ISSUE THREAD

**Issue by iamthemandarin** [stellar-expert/stellar-expert-explorer#784]
The overall traded volume is at 0 USD on stellar.expert for the EURC asset -
https://stellar.expert/explorer/public/asset/EURC-GAQRF3UGHBT6JYQZ7YSUYCIYWAF4T2SAA5237Q5LIQYJOHHFAWDXZ7NM

**Comment by orbitlens** [comment]
Fixed. Thanks for letting me know! And sorry for the inconveniences.
