### ISSUE TITLE
Inconsistencies in Content Hash

### ISSUE THREAD

**Issue by Julian-dev28** [stellar-expert/stellar-expert-explorer#814]
Reference: https://stellar.expert/explorer/public/staged-soroban-config/vMdIBVCY7OcPuX3DJxQQg6dyszwHIgzBbBNGQuxPxOkrPqTMhlrObmws6vnhmxMBzQkZHVj8IfiJvJtiodXG9Q%3D%3D

When using stellar.expert, you might notice a discrepancy in how content hashes and contract IDs are displayed compared to Stellar core.

**Content Hash Format**: Currently, stellar.expert shows the content hash in base64 format, which can be confusing for users accustomed to seeing it in hex format. It would be more intuitive if the content hash were displayed in hex format to match Stellar core and make it easier to interpret.

**Comment by Julian-dev28** [comment]
cc @MonsieurNicolas

**Comment by MonsieurNicolas** [comment]
it's not just core, other hashes in stellar.expert are hex (like tx hash or ledger hash)
