### ISSUE TITLE
different result in XDR view

### ISSUE THREAD

**Issue by macancrew** [stellar-expert/stellar-expert-explorer#833]
![image](https://github.com/stellar-expert/stellar-expert-explorer/assets/121643334/dc71dc3f-02f0-4eb0-8608-ab9d23c65b18)
hash : 49733acb71a89f689fc5b70d85a506a5f31551e8c119c1f86dc13719a0b3aee9
swap from 0.0092 to .0043246

but if view XDR  
![image](https://github.com/stellar-expert/stellar-expert-explorer/assets/121643334/c9e5ef18-2d8b-432a-a8d2-97d13f741a2f)

destination 0.0135246
![image](https://github.com/stellar-expert/stellar-expert-explorer/assets/121643334/9d41cc97-1277-45a4-8b86-86ebd4ccd590)

**Comment by orbitlens** [comment]
Thank you for the heads up. We fixed the problem.

**Comment by macancrew** [comment]
new report bug

https://github.com/stellar-expert/stellar-expert-explorer/issues/835

Pada Jum, 21 Jun 2024 pukul 23.13 OrbitLens ***@***.***>
menulis:
