### ISSUE TITLE
asset not clickable

### ISSUE THREAD

**Issue by macancrew** [stellar-expert/stellar-expert-explorer#835]
In the old version, when an asset was clicked it would open to that asset, now that's no longer the case

![image](https://github.com/stellar-expert/stellar-expert-explorer/assets/121643334/8e1415bf-d276-4171-b565-1e8ef2ecaccf)

**Comment by orbitlens** [comment]
Following user requests, we updated the default click action. The balance click switches the asset displayed in the balance change history below.
