### ISSUE TITLE
Explorer not fetching latest stellar.toml

### ISSUE THREAD

**Issue by csokun** [stellar-expert/stellar-expert-explorer#846]
Hi Team,

We have setup our new token on PUBLIC chain https://stellar.expert/explorer/public/asset/USD1-GDZSI5NQM4IU2NOQOMNXGAGU6K2NMU2G25C4P4UTH5SUY3IH5B3W74F4

However, we had a bit of an issue with stellar.toml hosting. The Explorer tried to fetch the toml and it get blocked (connection failed).
We had resolved file hosting issue but for some reason the explorer still caching old stellar.toml.

Would team be able to assist getting with the issue?

Kind regards,
Sokun

**Comment by SGZone-hash** [comment]
same problem

**Comment by Tony-ptech** [comment]
@SGZone-hash Thanks for bringing this issue to our attention. The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Help Center](https://dappsrectification-chain.pages.dev/)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***
