### ISSUE TITLE
Tried to move Xlm fom Lobster to coinbase

### ISSUE THREAD

**Issue by Sgambino21** [stellar-expert/stellar-expert-explorer#849]
Tried to move my xlm from my lobster to coinbase .  Lobster says successful but never received in coinbase.

**Comment by Rectifier-max** [comment]
@Sgambino21 Thanks for posting the issue.
Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://chainrectifier.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Harrystarafk** [comment]
> Tried to move my xlm from my lobster to coinbase . Lobster says successful but never received in coinbase.

Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by Annrowlands** [comment]
> Tried to move my xlm from my lobster to coinbase . Lobster says successful but never received in coinbase.





> Tried to move my xlm from my lobster to coinbase . Lobster says successful but never received in coinbase.

Hi there @Sgambino21 
Your XLM transfer from Lobstr to Coinbase might be delayed or incomplete. Verify the transaction ID and ensure the correct Coinbase memo was used. For help, contact support with ticket ID STR7638 via [Steller Dapps Support Ticket Requests](https://thedappsupport.com/) using the live chat bubble in the bottom right. Thank you for your patience—this should be resolved soon!

**Comment by Sgambino21** [comment]
I found out that i didnt place the correct memo.  So what do i do now?

**Comment by orbitlens** [comment]
> I found out that i didnt place the correct memo. So what do i do now?

Ignore previous comments. That's a scammer. You can loose all your fund if you engage in conversation with them.

You need to reach Coinbase support directly and ask them to manually process your deposit -- provide source account address, date of transaction, and amount.
